WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /session/86b8f8a3-6f91-4407-8c00-fede637d3bf9
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7709e05c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/86b8f8a3-6f91-4407-8c00-fede637d3bf9
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7709e03c8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/86b8f8a3-6f91-4407-8c00-fede637d3bf9
