WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4a5327048>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2210ce08-21f4-4d4e-a621-40a11fe5b101
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4a5327198>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2210ce08-21f4-4d4e-a621-40a11fe5b101
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4a5327278>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2210ce08-21f4-4d4e-a621-40a11fe5b101
